# URLs
USER_SERVICE_URL = 'user-manager:8080'
INVENTORY_SERVICE_URL = "inventory-service"
LLM_SERVICE_URL = "llm-service:8888"

# Endpoint templates
QUERY_SCHEMA_ENDPOINT_TEMPLATE = "http://{}/schema/propertyQuery"
PROPERTY_QUERY_ENDPOINT_TEMPLATE = "http://{}/queryProperties"
LLM_QUERY_ENDPOINT_TEMPLATE = "http://{}/generates/query"
TOKEN_VERIFICATION_ENDPOINT_TEMPLATE = "http://{}/verifyAccessToken"

# Endpoints
TOKEN_VERIFICATION_ENDPOINT = TOKEN_VERIFICATION_ENDPOINT_TEMPLATE.format(USER_SERVICE_URL)
QUERY_SCHEMA_ENDPOINT = QUERY_SCHEMA_ENDPOINT_TEMPLATE.format(INVENTORY_SERVICE_URL)
LLM_QUERY_ENDPOINT = LLM_QUERY_ENDPOINT_TEMPLATE.format(LLM_SERVICE_URL)
PROPERTY_QUERY_ENDPOINT = PROPERTY_QUERY_ENDPOINT_TEMPLATE.format(INVENTORY_SERVICE_URL)
